#!/usr/bin/env node
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium } from 'playwright-core';
import { APP, seedSession, signIn } from './lib/session.mjs';

const OUT = process.env.SHOT_OUT ?? 'shots';

/** Named so a diff says "users at phone width", not "shot-3". */
const WIDTHS = [
  { name: 'phone', width: 375, height: 812 },
  { name: 'tablet', width: 768, height: 1024 },
  { name: 'desktop', width: 1280, height: 800 },
];

const ROUTES = ['/', '/profile', '/users'];

/** Below this the shell is a drawer, so those widths get an extra open shot. */
const DESKTOP_MIN = 1024;

const slug = (route) => (route === '/' ? 'home' : route.replaceAll('/', ''));

async function main() {
  const auth = await signIn('shots');
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const browser = await chromium.launch({ channel: 'chrome' });
  const written = [];

  try {
    for (const { name, width, height } of WIDTHS) {
      const context = await browser.newContext({
        viewport: { width, height },
        deviceScaleFactor: 1,
        hasTouch: width < DESKTOP_MIN,
      });
      await seedSession(context, auth);

      const page = await context.newPage();

      for (const route of ROUTES) {
        await page.goto(`${APP}${route}`, { waitUntil: 'networkidle' });
        const file = join(OUT, `${slug(route)}-${name}.png`);
        await page.screenshot({ path: file, fullPage: true });
        written.push(file);
      }

      if (width < DESKTOP_MIN) {
        await page.goto(`${APP}/`, { waitUntil: 'networkidle' });
        await page.locator('#app-nav-toggle').click();
        await page.waitForTimeout(400);
        const file = join(OUT, `drawer-${name}.png`);
        await page.screenshot({ path: file });
        written.push(file);
      }

      await context.close();
    }
  } finally {
    await browser.close();
  }

  await writeFile(
    join(OUT, 'README.md'),
    `# Responsive screenshots

Generated by \`npm run shots\` — not committed, regenerate on demand.

To check a layout change, run it once on each side and compare the folders:

    SHOT_OUT=shots-before npm run shots
    SHOT_OUT=shots-after  npm run shots

${written.map((f) => `- ${f}`).join('\n')}
`,
  );

  console.log(`${written.length} screenshots → ${OUT}/`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
